server:
  port: 9002

spring:
  profiles:
    include: secret
    active: dev

  data:
    redis:
      port: 6379
      host: localhost
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true