spring:
  data:
    redis:
      port: 6379
      host: env-redis-1
db:
  url: jdbc:mysql://env-mysql-1:3306/ticketone


cookie:
  domain: localhost
  secure: false  # dev 환경에서는 false, prod 환경에서는 true로 설정