server:
  port: 9001

spring:
  profiles:
    active: dev
    include: secret
  data:
    redis:
      port: 6379
      host: localhost

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    hikari:
      auto-commit: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

jwt:
  expiration: 8640000

custom:
  instance-id: waiting-1