server:
  port: 9000

spring:
  profiles:
    active: dev
    include: secret
  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      auto-commit: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ON_SECRET
    password: ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
payment:
  toss:
    secret-key: ON_SECRET
    api-url: https://api.tosspayments.com/v1/payments/confirm
# JWT Configuration
jwt:
  expiration: 86400000

# Cookie Configuration
cookie:
  domain: localhost
  secure: false  # dev 환경에서는 false, prod 환경에서는 true로 설정

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - "*"
    - https://ticketone.site
    - https://www.app4.qwas.shop
    - http://www.app4.qwas.shop
    - https://login.aleph.kr
    - http://login.aleph.kr

sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth # 고정값
    client:
      id: ON_SECRET
      secret: ON_SECRET
    callback:
      url: https://api.main.ticketone.site/auth/google/callback # 유저 설정에 따라 변경 가능 (Redirect URI)
    token:
      url: https://oauth2.googleapis.com/token # 고정값
  kakao:
    url: https://kauth.kakao.com/oauth/authorize # 고정값
    client:
      id: ON_SECRET
      secret: ON_SECRET
    callback:
      url: https://api.main.ticketone.site/auth/kakao/callback # 유저 설정에 따라 변경 가능 (Redirect URI)
    token:
      url: https://kauth.kakao.com/oauth/token # 고정값