server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev
    include: secret
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/ticketone?rewriteBatchedStatements=true
    username: ON_SECRET
    password: ON_SECRET
    hikari:
      auto-commit: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 50
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ON_SECRET
    password: ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 180000  # 30 * 60 * 100 == 3분
  batch:
    job:
      enabled: false   # 서버 시작 시 자동 배치 job 실행 방지
    jdbc:
      initialize-schema: always  # 배치용 테이블 자동 생성 (개발 환경만)
    event-status-update:
      enabled: false

payment:
  toss:
    secret-key: ON_SECRET
    api-url: https://api.tosspayments.com/v1/payments
# JWT Configuration
jwt:
  expiration: 86400000

# Cookie Configuration
cookie:
  domain: localhost
  secure: false  # dev 환경에서는 false, prod 환경에서는 true로 설정

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - "*"
    - https://ticketone.site
    - https://www.app4.qwas.shop
    - http://www.app4.qwas.shop
    - https://login.aleph.kr
    - http://login.aleph.kr

sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth # 고정값
    client:
      id: ON_SECRET
      secret: ON_SECRET
    callback:
      url: https://localhost:3001/auth/google/callback # 유저 설정에 따라 변경 가능 (Redirect URI)
    token:
      url: https://oauth2.googleapis.com/token # 고정값
  kakao:
    url: https://kauth.kakao.com/oauth/authorize # 고정값
    client:
      id: ON_SECRET
      secret: ON_SECRET
    callback:
      url: https://localhost:3001/auth/kakao/callback # 유저 설정에 따라 변경 가능 (Redirect URI)
    token:
      url: https://kauth.kakao.com/oauth/token # 고정값

# 허용된 리다이렉트 도메인 설정
allowed:
  redirect:
    domains: localhost:3001,localhost:9000,code-bug.vercel.app


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

