redis:
  port: 6379
  host: env-redis-1
db:
  url: jdbc:mysql://env-mysql-1:3306/ticketone
  username: jiwoo

# Cookie Configuration for Production
cookie:
  domain: ticketone.site  # 실제 프로덕션 도메인
  secure: true  # HTTPS 필수

# CORS Configuration for Production
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - https://localhost:3000
    - https://localhost:3001
    - "*"
    - https://ticketone.site
    - https://www.app4.qwas.shop
    - http://www.app4.qwas.shop
    - https://login.aleph.kr
    - http://login.aleph.kr
