server:
  port: 9000

spring:
  profiles:
    active: dev
    include: secret
  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      auto-commit: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    api-url: ${TOSS_API_URL}
# JWT Configuration
jwt:
  expiration: 86400000

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - https://your-production-domain.com