server:
  port: 9000

spring:
  profiles:
    active: dev
    include: secret
  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      auto-commit: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

# JWT Configuration
jwt:
  secret: ON_SECRET
  expiration: 86400000

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - https://your-production-domain.com# JWT Configuration
